name: 'Setup Infrastructure'
description: 'Setup Terraform and Azure authentication for infrastructure deployment'
inputs:
  terraform-version:
    description: 'Terraform version to use'
    required: true
    default: '1.5.7'
  azure-client-id:
    description: 'Azure Client ID for OIDC authentication'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID for OIDC authentication'
    required: true
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
    
    - name: Set Terraform Environment Variables
      shell: bash
      run: |
        echo "ARM_CLIENT_ID=${{ inputs.azure-client-id }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ inputs.azure-tenant-id }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.azure-subscription-id }}" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        echo "ARM_USE_AZUREAD=true" >> $GITHUB_ENV